sudo docker run -p 3000:3000 \
    -e BPYP_POSTGRES_DIR_CONN="${BPYP_POSTGRES_DIR_CONN}" \
    -e BPYP_SUPABASE_URL="${BPYP_SUPABASE_URL}" \
    -e BPYP_SUPABASE_SERVICE_KEY="${BPYP_SUPABASE_SERVICE_KEY}" \
    -e BPYP_POSTGRES_JWT_SECRET="${BPYP_POSTGRES_JWT_SECRET}" \
    -e BPYP_WIT_URL="${BPYP_WIT_URL}" \
    -e BPYP_WIT_API_KEY="${BPYP_BEARER_API}" \
    bpyp-go:latest
